[package]
name = "mseq"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/jeudine/gbseq"
authors = ["Julien Eudine <julien@eudine.fr>"]

[dependencies]
midir = "0.9.1"
promptly = "0.3.1"
spin_sleep = "1.2.1"
thiserror = "1.0.57"


[profile.release]
lto = true
