[package]
name = "mseq_tracks"
version = "1.0.0"
edition = "2024"
license = "LGPL-2.1"
readme = "README.md"
repository = "https://github.com/MF-Room/mseq/tree/main/mseq_tracks"
authors = ["Julien Eudine <julien@eudine.fr>", "Marius Debussche <marius.debussche@gmail.com>"]
description = "Library for developing MIDI Sequencers."
keywords = ["midi", "music", "sequencer"]
categories = ["multimedia"]

[dependencies]
mseq_core = { version = "1.0.0", path = "../mseq_core" }
thiserror = "2.0.18"
midir = "0.11.0"
serde = {version = "1.0.228", features = ["derive"] }
csv = {version = "1.4.0"}
midly = "0.5.3"
fs-err = "3.3.1"
log = "0.4.33"
hashbrown = "0.17.1"
toml = "1.1.2"
itertools = "0.15.0"

[features]
default = ["std"]
std = []

