name: CI/CD

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: mseq
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2

      - name: Install Dependencies
        run: sudo apt-get install -y libasound2-dev
  
      - name: setup toolchain
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - name: cargo test
        run: cargo test --workspace --all-features

      - name: rustfmt
        run: cargo fmt --workspace -- --check

      - name: clippy
        run: cargo clippy --workspace --all-features --tests -- -D warnings

      - name: clippy no_std
        run: cargo clippy --workspace --no-default-features -- -D warnings
